### ISSUE TITLE
Sha1 fingerprint on login

### ISSUE THREAD

**Issue by kroeckx** [mkj/dropbear#116]
When I log in with my ed25519 key, the log shows:
```
authpriv.notice dropbear[2480]: Pubkey auth succeeded for 'root' with key sha1!! XX:XX:XX from 192.168.0.2:43248
```
I think what it's saying is that it generated a sha1 fingerprint from my Ed25519 key, but the "!!" give the impression that the key is somehow using sha1. Can you improve the message not to confuse people? Maybe you can also add the keytype, and show the fingerprint as sha256.

**Comment by mkj** [comment]
Ah yes, the sha!! is a leftover from back when md5 was what people expected, printed by the client not in logs. 
sha256 with base64 should be used.

**Comment by mkj** [comment]
https://github.com/mkj/dropbear/commit/6ad6210901ddc8886270b7668ed92734d45e183c prints the key type and a sha256 fingerprint
