### ISSUE TITLE
Suggestion: Enhancement to ensure dropbear doesn't get forever stuck calling getrandom() at early boot

### ISSUE THREAD

**Issue by RMerl** [mkj/dropbear#117]
On an embedded device, having dropbear attempt to generate keys too early in the boot process may result in the device getting forever stuck, as embedded devices such as routers often have very little interrupt activity to properly seed getrandom() during the earlier boot stage.

Currently, dropbear runs one non-blocking getrandom(), followed by a blocking one.  I suggest making the second getrandom() also non-blocking, so that way dropbear can fallback to using another source (such as /dev/urandom) rather than getting forever stuck.

One possible improvement would be to loop the non-blocking getrandom() calls with increasing wait time ( sleep(n*n++) ), until after a certain period of time (like 30 seconds) then a fallback to /dev/urandom is used.

**Comment by ynezz** [comment]
> On an embedded device, having dropbear attempt to generate keys too early in the boot process may result in the device getting forever stuck, as embedded devices such as routers often have very little interrupt activity to properly seed getrandom() during the earlier boot stage.

Can you be more specific here? What device/CPU and userspace/kernel is this about. OpenWrt supports wide range of embedded devices, ships dropbear by default and doesn't suffer with this issues.

**Comment by RMerl** [comment]
Asuswrt-Merlin (https://github.com/RMerl/asuswrt-merlin.ng).  When upgrading from a firmware that didn't support an ed25519 host key, the router would get stuck at boot time trying to generate it.  I worked around the issue by moving the initialization of  dropbear closer to the end of the boot process, at which point there has been enough interrupt activity to reach a sufficient level of entropy for getrandom().  Might be a better idea however for dropbear to ensure it can't get stuck on a neverending getrandom() call by providing a way out of it.

**Comment by mkj** [comment]
Getting stuck is kind of a deliberate feature, even if it's a bit awkward.
The alternative is to use /dev/urandom even if it hasn't been sufficiently seeded, which could result in easily guessable private keys or session keys. That would defeat the purpose of strong encryption, but would be hard to notice.

Moving it later in the boot process is a good approach, by that stage there has been enough hardware activity to seed the entropy pool.

**Comment by RMerl** [comment]
It's indeed a compromise between having a guarantee that keys are generated from a well seeded random generator, and avoiding potential deadlocks.  That's why I thought about just giving it a certain amount of time before falling back to using urandom as a safety measure to avoid deadlocks, and making sure the user gets notified about that fallback.  Up to you, your point of view is definitely a very valid one as well.

Linux kernel devs are well aware of these issues tied to getrandom()'s reliance on interrupts to generate entropy, which is why they added another source of entropy a few months ago based on timer jitter.  I saw they had quite a few discussions as to how to improve the getrandom() API.

**Comment by ynezz** [comment]
>  another source of entropy a few months ago based on timer jitter

FYI you can have the same in userspace via (jitterentropy-rngd)[https://github.com/smuellerDD/jitterentropy-rngd/] if the CPU is decent and has usable timer.

**Comment by RMerl** [comment]
> > another source of entropy a few months ago based on timer jitter
> 
> FYI you can have the same in userspace via [jitterentropy-rngd](https://github.com/smuellerDD/jitterentropy-rngd/) if the CPU is decent and has usable timer.

Thanks for the reference, I didn't know about this one (I only had heard of havegd).  Seems do do a pretty good job at quickly filling up the pool on this BCM4908 CPU (Cortex A53) based on my test, so I'll seriously consider adding it to the firmware's early boot process.
