### ISSUE TITLE
scp does nothing

### ISSUE THREAD

**Issue by acornblue** [mkj/dropbear#119]
Unable to copy authorized_keys using scp. There is no errors. It just sits there
$ scp authorized_keys pi@10.0.0.1:authorized keys

It worked 3 months ago. I checked history & nothing has changed... Same clean image of raspberry pi. Only Termux has been updated. Note: I can ssh into the server.

I ended up installing openssh to copy the file. On a whim, I switched back to dropbear & scp works with keys... 

I'm using dropbear (2020.81-1) on a pixel 3 with android 11 via termux. ssh server is running on a raspberry pi 4 with raspberry pi os 32bit release 1/11/2021

**Comment by MichaIng** [comment]
Dropbear does not include an SFTP server or the `scp` command-line utility, so this would always need to be installed separately. Did you install/setup either an SFTP server or `scp`?

I guess you use Raspberry Pi OS. To install `scp`, the easiest way is to install the standalone OpenSSH binaries:
```sh
apt install openssh-client
```
If SFTP is wanted (note that SCP basically is deprecated):
```sh
apt install openssh-sftp-server
```
These packages do not include the OpenSSH server, just the client (which includes `scp`) and the standalone SFTP server, which is a single executable as well, essentially. Dropbear, respectively the SSH clients automatically start these executables server-side to get SFTP/SCP transaction done.

**Comment by mkj** [comment]
I'm a bit surprised it wouldn't print any error message if scp or sftp was missing.
