### ISSUE TITLE
Support sha256 sums for fingerprints

### ISSUE THREAD

**Issue by aparcar** [mkj/dropbear#122]
Looking at `signkey.c` dropbear only support SHA1 or MD5 checksums, would it be possible to add SHA256 support?

**Comment by SvenRoederer** [comment]
relates to #116

**Comment by mkj** [comment]
SHA256 fingerprints are added in https://github.com/mkj/dropbear/commit/8b68eb55d9a0d8abc145575dd7d19cd2df111bd7
