### ISSUE TITLE
Help maintaining dropbear

### ISSUE THREAD

**Issue by manfred-kaiser** [mkj/dropbear#134]
If you are interested, I can help you in maintaining dropbear.

I can help you with code reviews for pull requests, testing new features and managing issues.

**Comment by mkj** [comment]
Thanks, that would be helpful. Feel free to look at anything that is easily mergable, I'll send you an email.

**Comment by manfred-kaiser** [comment]
Thanks for the invitation. 

Currently I'm documenting "trivial success authentication" #128 
I plan to publish the information in October.

What is the next release number? Will it be 2021.82?
