### ISSUE TITLE
ecdsa-sk and ed25519-sk

### ISSUE THREAD

**Issue by as400l** [mkj/dropbear#135]
Are there any plans supporting these ?

**Comment by mkj** [comment]
At the moment I don't have plans to implement it myself, though I wouldn't object if someone wants to implement it.

The biggest consideration seems to be that it would pull in external libraries.

**Comment by 35609902357** [comment]
@mkj Curve25519 is regarded to be [more secure and performant than RSA](https://docs.gitlab.com/ee/ssh/index.html#ed25519-ssh-keys). Please, consider implementing it. Someone even [forked dropbear](https://github.com/pts/pts-dropbear) just to add this feature. Maybe implement their code?

**Comment by mkj** [comment]
Dropbear already supports ed25519 key format and curve25519 key exchange.

This issue is about supporting U2F/FIDO keys for auth, the protocol is

https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f

**Comment by 35609902357** [comment]
@mkj I generated keys with openssh and they don't work with dropbear, they are ignored and I'm asked for a password. I thought the conversion tool was for the unsupported formats. Do I have to convert them to make them usable by dropbear?

**Comment by mkj** [comment]
Support for ecdsa-sk and ed25519-sk are now merged
