### ISSUE TITLE
ed25519 keys don't work

### ISSUE THREAD

**Issue by 35609902357** [mkj/dropbear#136]
If I generate `ssh-keygen -t rsa` and add the key to the server everything works as expected.
If I generate `ssh-keygen -t ed25519` and add the key to the server the key is not accepted.
I tried to use `dropbearconvert openssh dropbear id_ed25519 id_ed25519-dropbear`, but the output file seems broken.
How can I diagnose this issue?

**Comment by mkj** [comment]
dropbearconvert can't handle OpenSSH new key format, only the older style keys from `ssh-keygen -m PEM`, which start with `-----BEGIN RSA PRIVATE KEY-----` etc. It should print an error message that it can't convert.

ssh-keygen can't write ed25519 keys in PEM format. So you'll have to use `dropbearkey` to create the key. At some point I'll implement conversion for the newer format, or patches accepted.

The other ecdsa format keys should work OK for conversion, they have similar performance to ed25519, though not quite as fast.
