### ISSUE TITLE
Cleanup Initramfs port number configuration

### ISSUE THREAD

**Issue by softwarecreations** [mkj/dropbear#141]
Thanks for this great project. This issue is about config irregularities and hopeful cleanup.

This question is **only regarding Dropbear inside initramfs**. (not running Dropbear as a service or once booted)

### Incorrect documentation?

The readme mentions having DROPBEAR_PORT inside `/etc/default/dropbear`

However I've found in Debian 10 Buster and Debian 11 Bullseye, DROPBEAR_PORT in /etc/default/dropbear is completely ignored when Dropbear starts up inside initramfs. Instead, Dropbear looks at
`DROPBEAR_OPTIONS='-p 123'` inside /etc/dropbear-initramfs/config

## Question about the way it has been and is right now

1. In terms of properly configuring Dropbear for initramfs, do we ever need to set DROPBEAR_PORT inside /etc/default/dropbear?
2. Did this situation only start in Debian Buster or has Dropbear always worked this way on Debian? What about other distros?

## Just a comment
I find it strange that Dropbear inside initramfs actually uses stuff like DROPBEAR_(key-type) inside /etc/default/dropbear, but it ignores DROPBEAR_PORT inside `/etc/default/dropbear`. It's bizarre.

Some clarity on this would be great.

Perhaps some cleanup is in order?
Ideally Dropbear for initramfs could be configured with a single config file? ( only `/etc/dropbear-initramfs/config` )

## Suggested solution (cleanup)
Considering that `/etc/dropbear-initramfs/` already holds
* `/etc/dropbear-initramfs/config`
* `/etc/dropbear-initramfs/authorized_keys`
* `/etc/dropbear-initramfs/dropbear_foo_key`
* `/etc/dropbear-initramfs/dropbear_bar_key`
* `/etc/dropbear-initramfs/dropbear_baz_key`
I think it would be simplest to
1. Do not require `/etc/default/dropbear` to exist at all
2. `DROPBEAR_PORT` should work inside `/etc/dropbear-initramfs/config` and `DROPBEAR_OPTIONS='-p...` should not be required to set the port.

**Comment by mkj** [comment]
All that initramfs configuration comes from the Debian packaging not the core Dropbear package (this on github) -  better to report at https://bugs.debian.org

My guess is that some people want to run Dropbear on a different port inside the initramfs since it might have a different hostkey to the main system (which would load from an encrypted filesystem). A `DROPBEAR_PORT` config in the initramfs sounds sensible though.
