### ISSUE TITLE
dropbear seems to disable coredumps in child processes as well

### ISSUE THREAD

**Issue by slashdevslashurandom** [mkj/dropbear#145]
So, I was considering using dropbear as my SSH server, but I encountered this problem. When I SSH onto a machine and try to develop/debug stuff, I find out that coredumps are not only disabled for that session, but also that changing it is not allowed.

I discovered that the following source code line is the culprit:

https://github.com/mkj/dropbear/blob/26feb8f13e350adeb02c74bca82de24a8e9d211e/svr-main.c#L56

The original idea (to disable coredumps for `dropbear` itself, so that if it crashes, it doesn't end up revealing sensitive information in the coredump), seems very reasonable, but it seems like this setting also spreads onto whatever session is being launched under it, which in turn makes me unable to get coredumps from any of the programs I'm running in it.

Is there a way to prevent that from happening, or to otherwise re-enable core dumps for the session?

**Comment by mkj** [comment]
Ah that's a good point, I hadn't considered that. I'll look
how to resolve it.

**Comment by slashdevslashurandom** [comment]
Thanks a lot!
