### ISSUE TITLE
Kernel Panic when connecting via WireGuard

### ISSUE THREAD

**Issue by riggs** [mkj/dropbear#179]
Dropbear v2022.82
Wireguard  v1.0.20200827
Cortex A5

Usually the kernel spits out "Unable to handle kernel paging request at virtual address ..." but occasionally it's "Unable to handle kernel NULL pointer dereference at virtual address ..."

I have stack traces, but they don't look especially useful.

**Comment by mkj** [comment]
That sounds like it's running out of memory.

**Comment by riggs** [comment]
This happens when there's 86M of memory free. I can also ssh from the effected machine to another host.

**Comment by riggs** [comment]
This is the setup on the machine:
```
# wg
interface: wg0
  public key: <snip>
  private key: (hidden)
  listening port: 34098

peer: <snip>
  preshared key: (hidden)
  endpoint: 73.62.215.195:51820
  allowed ips: 172.16.0.0/16, 10.0.0.0/16
  latest handshake: 15 seconds ago
  transfer: 124 B received, 180 B sent
  persistent keepalive: every 25 seconds

# ifconfig
<snip>
wg0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:172.16.0.3  P-t-P:172.16.0.3  Mask:255.255.0.0
          UP POINTOPOINT RUNNING NOARP  MTU:1420  Metric:1
          RX packets:11 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:472 (472.0 B)  TX bytes:392 (392.0 B)
```

**Comment by mkj** [comment]
Seems like it has to be a kernel bug (or wireguard module if it's out of tree). Can you try a newer version of those?

I'll close this since it doesn't seem directly related to Dropbear.
