### ISSUE TITLE
Dropbear server breaks virt-viewer remote console display

### ISSUE THREAD

**Issue by clipcarl** [mkj/dropbear#188]
Hello. On Alpine Linux 3.16.2 (Musl C library) the default Dropbear server (2022.82) seems to break displaying remote libvirt VM consoles in virt-viewer on the client when Dropbear is the SSH server on the VM host.

I noticed that the problem didn't occur when I ran the Dropbear server manually from the command line to debug. Digging further, it appears that the problem only occurs when the "dropbear" command is run with its full path. For some reason this causes Dropbear server to spawn new processes for connections with an undocumented "-2" option which the source code seems to suggest is part of some sort of re-exec "feature." Editing my Dropbear startup scripts on my servers to not use the full path to the binary on startup fixed the issue for me but is obviously not ideal. Thanks!

**Comment by mkj** [comment]
Would you be able to run `strace -f -e execve,execveat -s 300 -p {pid of dropbear server}`, then paste the log file (shouldn't contain anything too sensitive, though check it over first). The `-2` should just be running the same path as the main listening server, something might be going wrong there.
