### ISSUE TITLE
Connecting via a web client using a web proxy

### ISSUE THREAD

**Issue by AlexanderZhirov** [mkj/dropbear#202]
I have a large number of embedded systems that use Dropbear as an SSH server. The task is to make them freely accessible using a web application. To do this, I have developed an internal site in which I want to implement an SSH client based on web sockets. For this purpose, I used a ready-made open source product [SSHy](https://github.com/stuicey/SSHy). Since he was not active in development for a long time, I used a [modified fork](https://github.com/drgrussell/SSHy) of this project. I used [websockify](https://github.com/novnc/websockify) as a proxy server.

[The problem is that there is a hang during the connection process](https://github.com/stuicey/SSHy/issues/45#issuecomment-1345261005). As far as my knowledge allows me to understand all this, I mean that the problem is in the handshake process - at some stage of the packet exchange, some kind of failure occurs somewhere. I can't quite identify it, because I don't fully understand the whole concept of SSH.

![изображение](https://user-images.githubusercontent.com/37277056/206897820-76511528-8ae6-4ade-ada7-2f49334ac5d2.png)

Using tcpdump, I took a packet dump. It can be seen that the connection is happening, but the process freezes.

On the server side, you can also see that the connection is taking place and the Dropbear child process appears.

![изображение](https://user-images.githubusercontent.com/37277056/206897925-087ab8d7-09ba-460e-ba41-de126ef3fcd6.png)

I tried to join the OpenSSH server using this client and the connection was successful. I mean that the exchange process happens somehow differently. And how exactly - I can't understand. I ask for guru's help.

[pcap dropbear connection file](https://github.com/mkj/dropbear/files/10201870/dropbear.zip)

**Comment by mkj** [comment]
I've made a try at fixing the SSHy version parsing, though couldn't get index.html to work with my websocksify (didn't even get to connecting) - you can see if it works or modify as required.

**Comment by mkj** [comment]
Seems to be working now with SSHy changes discussed in https://github.com/mkj/SSHy/commit/7ac39415d49494e634f1121fb44ba9468b2fa9a4

**Comment by AlexanderZhirov** [comment]
Thanks! :smiley:
