### ISSUE TITLE
version22.83   where i add -z label in file

### ISSUE THREAD

**Issue by yuhongwei380** [mkj/dropbear#203]
in dropbear  version 22.83   where i add -z label in file ?

**Comment by mkj** [comment]
It doesn't look like OpenWRT has any custom argument configuration, so you would need to edit /etc/init.d/dropbear and add it to the line

```
        procd_set_param command "$PROG" -F -P "$pid_file"          
```
as
```
        procd_set_param command "$PROG" -F -P "$pid_file" -z
```

**Comment by yuhongwei380** [comment]
it is work! thanks
