### ISSUE TITLE
Missing break in switch(type) in dropbearkey.c::check_signkey_bits() 

### ISSUE THREAD

**Issue by yshsu168** [mkj/dropbear#208]
#if DROPBEAR_DSS
                case DROPBEAR_SIGNKEY_DSS:
                        if (bits != 1024) {
                                dropbear_exit("DSS keys have a fixed size of 1024 bits\n");
                                exit(EXIT_FAILURE);
                        }          
                        break; // Need to add this line.    
#endif                                  
                default:

**Comment by mkj** [comment]
Thanks
