### ISSUE TITLE
[Q] Dropbear agent key is visible in ssh connection but fail to fetch them with ssh_fetch_identitylist: agent refused operation

### ISSUE THREAD

**Issue by 0anton** [mkj/dropbear#213]
I observe some weird behaviour with regard to use of forwarded keys.

I access my router (OpenWRT 22.03) over SSH enabling key forwarding:

```
ssh -A root@192.168.xx.yy -p 2222
```

The socket for agent connection is successfully created and has proper rights:
```
root@gw-bsb:~/.ssh# env | grep SSH
SSH_AUTH_SOCK=/tmp/dropbear-19ec2148/auth-cea63dfa-6
SSH_TTY=/dev/pts/0

root@gw-bsb:~# ls -l  /tmp/dropbear-19ec2148/auth-cea63dfa-6
srwxr-xr-x 1 root root 0 Jan  8 00:55 /tmp/dropbear-19ec2148/auth-cea63dfa-6
```

Key are also visible to the ssh client:

```
root@gw-bsb:~/.ssh# ssh-add -v -l
1024 SHA256:xx yy (RSA)
256 SHA256:zz yy (ED25519)
2048 SHA256:xxx iii (RSA)
```

However client is not able to use keys in real ssh connections:
```
$ ssh -v git@github.com
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: ssh_fetch_identitylist: agent refused operation
```

OpenWRT uses a dropbear implementation of ssh client:
```
root@gw-bsb:~/.ssh# dropbear -V
Dropbear v2022.82
```

Older versions of OpenWRT didn't have problems with the key forwarding.

```
root@bsb:~# ssh -V
Dropbear v2020.81

root@bsb:~# ssh -v git@github.com
WARNING: Ignoring unknown option -v
Hi 0anton! You've successfully authenticated, but GitHub does not provide shell access.
```

**How can I fix this?**

**Comment by mkj** [comment]
> ```
> $ ssh -v git@github.com
> debug1: rekey in after 134217728 blocks
> debug1: get_agent_identities: ssh_fetch_identitylist: agent refused operation
> ```
> 
> OpenWRT uses a dropbear implementation of ssh client:
> 
> ```
> root@gw-bsb:~/.ssh# dropbear -V
> Dropbear v2022.82
> ```

That `get_agent_identities` message is from openssh client, not dropbear client. What does `ssh -V` print on gw-bsb?

I wonder if perhaps the ssh-agent version doesn't support RSA with sha256 signatures, what version is it?

**Comment by 0anton** [comment]
Hi Matt, thank you very much for your hint!

It prints:

```
root@gw:~# ssh -V
OpenSSH_8.9p1, OpenSSL 1.1.1q  5 Jul 2022
```

So, it is not an _dropbear_ client.

Maybe _ssh_ client is not compatible with _dropbear_ server?
The incoming connection to _gw-bsb_ router is over _dropbear_ sshd daemon, but the cli client is apprently a an OpenSSH one.


```
root@gw:~# opkg list-installed | grep drop
dropbear - 2022.82-2
root@gw:~# opkg list-installed | grep ssh
openssh-client - 8.9p1-1
openssh-client-utils - 8.9p1-1
openssh-keygen - 8.9p1-1
openssh-sftp-server - 8.9p1-1
```

I'll try to move openssh client...

**Comment by 0anton** [comment]
And yes, it worked!
```
root@gw:~# ssh git@github.com
Hi 0anton! You've successfully authenticated, but GitHub does not provide shell access.
```
