### ISSUE TITLE
DROPBEAR_SVR_MULTIUSER sanity check false positive fail

### ISSUE THREAD

**Issue by davidatrsp** [mkj/dropbear#214]
Hejsa
Disabling DROPBEAR_SVR_MULTIUSER config on kernel 5.10 without CONFIG_MULTIUSER produces a failed sanity check when initiation  a session.
Traced the issue down to https://github.com/mkj/dropbear/blob/9defeb477aebf0eb575885eb1fd4a4330ce52531/common-session.c#L75 . The "getuid()" doesn't set errno to "ENOSYS" as expected.
Looked into the kernel source and looks like "getuid()" syscall is always present, independently of CONFIG_MULTIUSER. Also, when CONFIG_MULTIUSER is disabled "getuid()" always succeeds and returns "0". This behaviour is present at leats from kernel 4.9.
My workaround  is to change "getuid" syscall into "getgroups". The "getgroups" has the expected behaviour, it is only present when the kernel is configured with CONFIG_MULTIUSER.

**Comment by mkj** [comment]
Thanks, I'll fix that. I wonder if that means no one has used the disabled-`DROPBEAR_SVR_MULTIUSER` functionality since it was added...
