### ISSUE TITLE
 How to reduce the waiting time for client login 

### ISSUE THREAD

**Issue by jhkwei** [mkj/dropbear#215]
Waiting time for login is too long

**Comment by mkj** [comment]
Can you send a log of the client side? `ssh -vvv` on Linux, or a PuTTY log on windows.

What platform is the server?

**Comment by mkj** [comment]
Also if you can point out where the delay is in the log, that would help.

**Comment by jhkwei** [comment]
ssh -v root@192.168.0.200
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.0.200 [192.168.0.200] port 22.
debug1: Connection established.
debug1: identity file /home/shenwei/.ssh/id_rsa type -1
debug1: identity file /home/shenwei/.ssh/id_rsa-cert type -1
debug1: identity file /home/shenwei/.ssh/id_dsa type -1
debug1: identity file /home/shenwei/.ssh/id_dsa-cert type -1
debug1: identity file /home/shenwei/.ssh/id_ecdsa type -1
debug1: identity file /home/shenwei/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/shenwei/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/shenwei/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/shenwei/.ssh/id_ed25519 type -1
debug1: identity file /home/shenwei/.ssh/id_ed25519-cert type -1
debug1: identity file /home/shenwei/.ssh/id_ed25519_sk type -1
debug1: identity file /home/shenwei/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/shenwei/.ssh/id_xmss type -1
debug1: identity file /home/shenwei/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: Remote protocol version 2.0, remote software version dropbear_2019.78
debug1: no match: dropbear_2019.78
debug1: Authenticating to 192.168.0.200:22 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:eEXNoaJv1qaEqv9d0JHOSXA1gxT4cM8Ng0esGAktWSo
debug1: Host '192.168.0.200' is known and matches the RSA host key.
debug1: Found key in /home/shenwei/.ssh/known_hosts:20
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: shenwei@ubuntu RSA SHA256:0wqe8Qq1HZ+8Bz/3lRPsSxPfRcHInEkKBVt0+RdDGyg agent
debug1: Will attempt key: /home/shenwei/.ssh/id_rsa 
debug1: Will attempt key: /home/shenwei/.ssh/id_dsa 
debug1: Will attempt key: /home/shenwei/.ssh/id_ecdsa 
debug1: Will attempt key: /home/shenwei/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/shenwei/.ssh/id_ed25519 
debug1: Will attempt key: /home/shenwei/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/shenwei/.ssh/id_xmss 
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: shenwei@ubuntu RSA SHA256:0wqe8Qq1HZ+8Bz/3lRPsSxPfRcHInEkKBVt0+RdDGyg agent
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/shenwei/.ssh/id_rsa
debug1: Trying private key: /home/shenwei/.ssh/id_dsa
debug1: Trying private key: /home/shenwei/.ssh/id_ecdsa
debug1: Trying private key: /home/shenwei/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/shenwei/.ssh/id_ed25519
debug1: Trying private key: /home/shenwei/.ssh/id_ed25519_sk
debug1: Trying private key: /home/shenwei/.ssh/id_xmss
debug1: Next authentication method: password
root@192.168.0.200's password: 
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
root@192.168.0.200's password: 
debug1: Authentication succeeded (password).
Authenticated to 192.168.0.200 ([192.168.0.200]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LC_ADDRESS = en_US.UTF-8
debug1: Sending env LC_NAME = en_US.UTF-8
debug1: Sending env LC_MONETARY = en_US.UTF-8
debug1: Sending env LC_PAPER = en_US.UTF-8
debug1: Sending env LANG = zh_CN.UTF-8
debug1: Sending env LC_IDENTIFICATION = en_US.UTF-8
debug1: Sending env LC_TELEPHONE = en_US.UTF-8
debug1: Sending env LC_MEASUREMENT = en_US.UTF-8
debug1: Sending env LC_TIME = en_US.UTF-8
debug1: Sending env LC_NUMERIC = en_US.UTF-8
root@RK356X:~#

**Comment by mkj** [comment]
Thanks. What step does it wait at?

**Comment by jhkwei** [comment]
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
#waiting in here
debug1: Remote protocol version 2.0, remote software version dropbear_2019.78

**Comment by jhkwei** [comment]
The current version is OK

**Comment by mkj** [comment]
Perhaps it was related to the random entropy source, that changed in 2020.79.
