### ISSUE TITLE
Support OpenSSH's StrictHostKeyChecking option with accept-new flag

### ISSUE THREAD

**Issue by Zepmann** [mkj/dropbear#226]
From the [ssh_config man page](https://man.openbsd.org/ssh_config):

> If this flag is set to **accept-new** then ssh will automatically add new host keys to the user's known_hosts file, but will not permit connections to hosts with changed host keys.

This is useful for automated management of (new) hosts. This is also more secure compared to using `-y` since it stores the host key in known_hosts, therefore not requiring `-y` in future sessions when connecting to the same host.

Example usage:
```
dbclient -oStrictHostKeyChecking=accept-new user@somenewhost "echo yes"
```

Alternatively:
Please include functionality from `ssh-keyscan` to allow printing host keys of (new) hosts.

Example usage (where `-S` is a new switch and `-t ed25519` limits the output to the corresponding key type):
```
dbclient -S -t ed25519 somenewhost
```
Example output:
```
somenewhost ssh-ed25519 ABCDE(...)
```

For compactness over functionality, the requested functionality could be limited to just `-S`, to have the output of all offered keys filtered elsewhere.

**Comment by stokito** [comment]
The `-y` flag is already used by the openssh-client:

> -y Send log information using the syslog(3) system module.  By default this information is sent to stderr.

So to make a compatible scripts it would be great to use the StrictHostKeyChecking instead.
It's used by the OpenWrt sshtunnel script.
