### ISSUE TITLE
Authentication error | No auth methods could be used

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [mkj/dropbear#228]
Hello,

I am tyring to ssh to a remote server using dropbear from my embedded board (with custom `Linux` distribution built using `yocto`).
When I try to establish connection I get
`ssh: Connection to device@example.com:22 exited: No auth methods could be used.`

ssh command I am using:
`ssh -i <>/.ssh/id_ecdsa -p 22 -R <remote_port>:localhost:22 device@example.com`

The <>/.ssh/id_ecdsa private key is generated using
`dropbearkey -f /home/root/.ssh/id_ecdsa -t ecdsa -b 256`

Also, I have added pub key to `authorized_keys` in `/home/root/.ssh/` with
`dropbearkey -y -f id_ecdsa | grep "^ecdsa-sha2-nistp256 " >> authorized_keys`

dropbear version
`Dropbear SSH client v2017.75`

Can anyone please let em know what is the issue here and how to resolve it?

Thanks in advance

**Comment by mkj** [comment]
What is the output if you run ssh as `ssh -vvv -i ....` for verbose logs?

Is there anything in the /var/log/syslog or auth.log or similar on the server?
