### ISSUE TITLE
Use git submodules for libraries

### ISSUE THREAD

**Issue by GravisZro** [mkj/dropbear#231]
Right now `libtomcrypt` and `libtommath` are both included inside the `dropbear` code repository. This is a bad practice for multiple reasons. I highly suggest that instead of including the code in the repo that you instead include these libraries as git submodules.

**Comment by mkj** [comment]
It seems like extra complication to me - what are the reasons?

**Comment by GravisZro** [comment]
The most important reason is that using submodules reduces the chances of making mistakes/falling behind when it comes to updating the code of each library. So, it's a security matter because you're only human.

**Comment by mkj** [comment]
libtomcrypt/libtommath updates infrequently enough that doing a 3-way merge between the previous (1.18.2) version, Dropbear's current subdir, and the new upstream git repo isn't much effort. That has just as much chance of going wrong as doing the merge in submodules, and is easier for everyone to check out and just use.
