### ISSUE TITLE
Extracting SCP transfer progress and identifying start in C++ program

### ISSUE THREAD

**Issue by okashany** [mkj/dropbear#235]
Within my C++ program, I am invoking SCP and using dup2 to redirect the progress to a log file. Here is a snippet of the relevant code:
```
int fd = open(logfile, O_CREAT | O_WRONLY, 0600);
dup2(fd, 1);
dup2(fd, 2);
close(fd);

// Execute the SCP command: "scp -v <src> <dest>" env: "DROPBEAR_PASSWORD=<pass>"
execvpe(cmd, argv, envp);
```
The transfer is successful, and the log file contains the following:
```
Executing: program /usr/bin/dbclient host <ip>, user <usr>, command scp -v -f <file>
/usr/bin/dbclient:
scp: debug1: fd 3 clearing O_NONBLOCK
Sink: C0644 <size> <file>
Sending file modes: C0644 <size> <file>
```
I have a few questions:

1. Currently, I rely on searching for the string "Sending file modes" in the log file to determine when the transfer starts. Are there better methods to identify when the transfer has started more effectively?

2. While inspecting the log file, I notice that the progress updates I expect are missing, and I only encounter the message "scp: debug1: fd 3 clearing O_NONBLOCK". Is there a way to capture the progress updates in the log file?

Thank you for your assistance!

**Comment by mkj** [comment]
By default dropbear's scp binary is built without the scp progress meter. You can compile with "SCPPROGRESS=1 make scp" and it will enable that. Then I guess you can parse the output.

**Comment by okashany** [comment]
I compile with "SCPPROGRESS=1". I can see the progress when running the same command from the terminal.
Perhaps it is related to my issue with scp that is running in background? https://github.com/mkj/dropbear/issues/234
Many thanks!
