### ISSUE TITLE
Extracting public key from OpenSSH certificate

### ISSUE THREAD

**Issue by okashany** [mkj/dropbear#238]
Hi,

I'm trying to add a host as a known host on the user's side after receiving its self-signed openSSH certificate.
If I understand correctly, after receiving the certificate on the user's side, I need to extract the public key from the certificate and add it to the ~/.ssh/known_host file, or /etc/dropbear/dropbear_rsa_host_key. Is that correct?
If so, how can I extract the public key from the openSSH certificate?
I tried to use dropbearconvert but it generates an error:
`dropbearconvert openssh dropbear ssh_host_ed25519_key-cert.pub host.pub
Error: File does not begin with OpenSSH key header
Error reading key from 'ssh_host_ed25519_key-cert.pub'`
Probably because this program should receive a public key and not a certificate (the file begins with "ssh-ed25519-cert-v01@openssh.com").

Any suggestions or insights on these matter would be most welcome.
Thanks!

**Comment by mkj** [comment]
Dropbear doesn't support OpenSSH certificates, sorry

**Comment by okashany** [comment]
Thanks for the quick response.
Is there another way to use SSH certificates between a host with openSSH and a user with DropbearSSH?

**Comment by okashany** [comment]
The second option, hosy key. I'm trying to add the server to the known hosts list prior the SCP transfer.

**Comment by mkj** [comment]
OK right. I would expect there also be be a non-certificate public key on the server that you can copy over. On my OpenSSH servers (without certificates) there's /etc/ssh/ssh_host_ed25519_key.pub , or ssh_host_rsa_key.pub , that should be able to be copied directly to ~/.ssh/known_hosts. Dropbear will only request non-certificate hostkey authentication, so those will work OK.

**Comment by okashany** [comment]
Thanks! Unfortunately, I'm forced to use certificates because the user API for file transfer contains only a certificate field.
Assuming the host uses Dropbear SSH, how do I generate a self-signed certificate? On the user's side, how do I add the host to the known hosts list using the certificate?
Many thanks

**Comment by mkj** [comment]
If you just "dbclient hostname" and choose yes to accept the key, it should get added to ~/.ssh/known_hosts. You could then copy that entry last entry in the file for that hostname if you need it on other systems. Dropbear will only request normal host keys not certificates, so it'll work fine. (If you use OpenSSH client it might request a certificate instead, not sure).
