### ISSUE TITLE
dropbear for lwip

### ISSUE THREAD

**Issue by Flynnsin** [mkj/dropbear#239]
Can dropbear run on a real-time operating system like freertos, with the lwip network protocol stack

**Comment by mkj** [comment]
Not easily. A couple of alternatives would be https://github.com/wolfSSL/wolfssh (seems production ready) or https://github.com/azonenberg/staticnet/tree/master/ssh (not sure it's been used much).

I've been working on my own lower-level SSH implementation "Sunset SSH", though it would need some integration effort to link into freertos. https://github.com/mkj/sunset

**Comment by Flynnsin** [comment]
Thank you for your advice, and please ask me again, if I want to implement ssh tunneling technology through freertos+lwip, what scheme should I adopt and what source code should I use
