### ISSUE TITLE
key-based authentication

### ISSUE THREAD

**Issue by okashany** [mkj/dropbear#240]
I have a few questions regarding user and server authentication with DropbearSSH:

1.	User authentication:
We are looking to avoid receiving and storing the user's password, as it raises security concerns. Does DropbearSSH support key-based authentication?

2.	Remote server authentication:
I have two servers, A and B, where server A runs OpenSSH, and server B runs DropbearSSH. My objective is to run SCP from server B without any interactive sessions:
scp user@serverA:/path/to/file /target/path/serverB
Here's the approach I've taken so far:
On server A, I executed the following command to discover the self-public key:
ssh-keyscan -t ed25519 ServerA
Then, I copied the public key from the response and added it to the ~/.ssh/known_hosts file on server B. It appears to be working correctly, and server B now recognizes server A.
I would like to know if there are any security risks associated with the approach I presented above. Are there alternative methods for performing authentication, considering that ssh-copy-id cannot be used as server B running DropbearSSH?

Thank you for your time and assistance.
Orit

**Comment by mkj** [comment]
Dropbear supports SSH public key authentication (though not certificates). The public key format is the same as OpenSSH (the entries in ~/.ssh/authorized_keys). The private key format is different but can be converted with `dropbearconvert` program if needed.

Manually adding the response to ~/.ssh/known_hosts is a good approach.

You can grab https://github.com/openssh/openssh-portable/blob/master/contrib/ssh-copy-id from OpenSSH, it's just a shell script. Note that some previous versions of that script are broken for Dropbear servers (not a problem in this case here). All the script does is copy the `ssh-ed25519 ....` public key line to ~/.ssh/authorized_keys on the server, so you could do that manually as an alternative.
