### ISSUE TITLE
Dropbear limited scalability

### ISSUE THREAD

**Issue by alekseiplotnikov** [mkj/dropbear#276]
Hi, I am working on a project that has thousands of devices running SSH tunnels to a single server. I am considering using Dropbear as an SSH daemon because of the very small memory footprint per connection. In order to better understand if Dropbear would fit our requirements I ran a scalability test of running 10K connections to a server. 

During the test I was increasing the number of connections by a 1K and after having 3-4K active connections I saw that no new connections were being created. On the client side new connections were timing out and on the server side Dropbear daemon had very high CPU usage, mostly waiting for system requests. When I ran strace on the Dropbear process, I found out that most of the time it was waiting on reading from the `/proc/timer_list` file. As I understand, Dropbear  [reads](https://github.com/mkj/dropbear/blob/aa37404398482f72fda113541a9a46985f6f2ec9/src/dbrandom.c#L273) this file as a source of entropy during every new connection creation, but on systems with many processes reading the timer_list can take several seconds and client connections time out as a result. I tried to disable the line in the code, rebuild the package and install it to the server. After that Dropbear was able to scale up to 10K active connections without any problem and CPU load was quite low. 

I understand that `/proc/timer_list` is a good source of entropy and my use case of having thousands of connections on a server is rather uncommon, so I am not sure if any fix or change is needed. But we definitely have a scalability problem here and I would like to share my findings in this issue.

I must say that other than this problem I am very impressed with Dropbear performance, memory usage and scalability. I was able to run 10K tunnels on a relatively small virtual machine with 2 CPU and 4GB of memory (t3.medium) and everything was working just fine. For OpenSSH I would need an instance several times larger and with 10-15 times more memory. That’s amazing, thanks for working on this project!

**Comment by mkj** [comment]
Thanks, I've removed that now.

Possibly the whole lot of `process_file()` in `seedrandom()` could be revisisted - my understanding is that the Linux kernel has improved entropy gathering since that was written.
