### ISSUE TITLE
how to set the unlock time for user using dropbear? 

### ISSUE THREAD

**Issue by Blanceone** [mkj/dropbear#279]
hello, I want to set an unlock time for users whose number of authentications exceeds the maximum authentication limit. but i cant find the command in -help. someone know how to do this?

**Comment by mkj** [comment]
Dropbear doesn't keep track of failed auth attempts (apart from a per-connection limit). Something like fail2ban might do what you want?

**Comment by Blanceone** [comment]
> Dropbear doesn't keep track of failed auth attempts (apart from a per-connection limit). Something like fail2ban might do what you want?

yes, that is what i want to do. seem its impossible do this with dropbear now. thank you.

**Comment by Git-Yousfi-Neji** [comment]
> hello, I want to set an unlock time for users whose number of authentications exceeds the maximum authentication limit. but i cant find the command in -help. someone know how to do this?

Hello,
I created a patch that could help you, if a user failed to type the valid password for over maximum authentication tries defined by -T option, the IP address will be banned for DEFAULT_BAN_TIME seconds.
[dropbear_patch.zip](https://github.com/mkj/dropbear/files/14853260/dropbear_patch.zip)
