### ISSUE TITLE
SSH command execution will overwrite stderr 

### ISSUE THREAD

**Issue by eSotoIoT** [mkj/dropbear#286]
dropbear ssh command execution will mess with `stderr`.

## How to reproduce 
Execute the following
```
remote_name=some_user    # edit this
remote_host=some_host    # edit this
echo "first line" > /tmp/foo
ssh -q $remote_name@$remote_host cat nonexistent_file.txt &>> /tmp/foo
```
Insert password then 
```
cat /tmp/foo
```

### Current output  (as in `Dropbear SSH client v2022.83`)
```
cat: can't open 'nonexistent_file.txt': No such file or directory
```

### Expected output 
```
first line
cat: can't open 'nonexistent_file.txt': No such file or directory
```

## Comments
According to my test, this behaviour doesn't manifest if a non-empty banner is received. That is, if remote_host has a non-empty banner and `-q` option is not used.

**Comment by eSotoIoT** [comment]
Hi there again.
The previous test was done in an armv7 embedded system. 

Recent tests show that dropbear ssh client is also messing with stdout.

This time I'm using an [oldish docker container](https://github.com/danielkza/docker-dropbear-static) with Dropbear SSH client v2019.78 in an Ubuntu host machine, 
```
Linux 6.5.0-25-generic 
#25~22.04.1-Ubuntu 
x86_64 x86_64 x86_64 
GNU/Linux
```

The test:

```
~ ❯ sudo docker run -it quay.io/danielkza/dropbear-static sh 
/ # ssh --help
WARNING: Ignoring unknown option --
Dropbear SSH client v2019.78 https://matt.ucc.asn.au/dropbear/dropbear.html
Usage: ssh [options] [user@]host[/port][,[user@]host/port],...] [command]
-p <remoteport>
...

/ # echo hi > test
/ # cat test 
hi
/ # ssh root@10.1.10.1 uname >> test

Host '10.1.10.1' is not in the trusted hosts file.
***************************************************************** (CENSORED line)
Do you want to continue connecting? (y/n) y
root@10.1.10.1's password: 
/ # cat test 
Linux
```

Notice the missing `hi` line in `test` file.

**Comment by mkj** [comment]
Thanks. Surprised that's never been reported before (that I know of)
