### ISSUE TITLE
dropbear hangs when bringing down secondary network interface

### ISSUE THREAD

**Issue by nicolaspanel** [mkj/dropbear#287]
Hi 
First thank you very much for maintaining dropbear, it has been very useful for us over the last few year :)

Recently we are facing a new issue though: 
script `/scripts/init-bottom` hangs when bringing down server's secondary network interface which is not even plugged

exact logs looks like
```
Begin: Running /scripts/local-bottom … done.
Begin: Running /scripts/init-bottom … Begin: stopping dropbear … done.
Begin: Bringing down enp69s0 … done.
Begin: Bringing down enp71s0 … 
[HANGS A WHILE THEN…]
INFO: task kworker/u256:1:463 blocked for more than 1087 seconds.
```

using option `IFDOWN='enp69s0'` allow us to fully execute `/scripts/init-bottom` but then ubuntu do not start properly.  it seems that nfs is not properly configured and, for example, `sudo` is unusable (`strace sudo su` indicates uid mismatches).

Does anyone have an idea why `/scripts/init-bottom` suddenly fail while it has been working for months ? May this be a hardware issue ?
Is there a way to bypass dropbear and boot directly on the underlying ubuntu (20.04)  ?

**Comment by mkj** [comment]
I don't think this is a dropbear problem, more like a problem with NFS in initramfs perhaps?

Is NFS mounted over `enp69s0`? I wonder if it needs to be mounted first, before taking that interface down. Tasks blocking forever certainly seems like a remote-filesystem-unreachable-network problem.
Not sure why it would have changed recently.

**Comment by mkj** [comment]
> Is there a way to bypass dropbear and boot directly on the underlying ubuntu (20.04) ?

Forgot this part - try `apt remove dropbear-initramfs` if you don't need Dropbear in initramfs (iirc dropbear-initramfs was previously installed by default, but newer dropbear packages only install it on request)

**Comment by nicolaspanel** [comment]
thanks @mkj for your answer !
I finally decided to to reinstall ubuntu from scratch and network & filesystem issues were still there…
It confirms that it is NOT dropbear related :point_right: I close this issue
Thanks again for sharing dropbear, it is great and really helpfull tool :pray:
