### ISSUE TITLE
option for authorized_keys path

### ISSUE THREAD

**Issue by Niculuse** [mkj/dropbear#325]
Hi, I need to specify a different authorized_keys file path from ~/.ssh/authorized_keys. Could you tell me how to modify the source code to achieve my goal? Maybe, you can support this function in the next release. Thanks.

**Comment by worm001** [comment]
If this option could be added, that would be great! This feature is quite practical!

**Comment by worm001** [comment]
Or is there any expert who can provide guidance on how to modify the source code to achieve this function?

**Comment by worm001** [comment]
There is an option [ -D ] displayed in the file [dropbear/manpages/dropbear.8], which literally means it is used to specify the authorized_keys file directory. However, this option cannot be used after compilation. Which file in the source code needs to be modified to enable this feature?

**Comment by worm001** [comment]
At present, modifying the content of the [svr-authpubkey.c] file can achieve the goal of not using authorized_keys in the. ssh directory. Let's use it first~It's better to wait for the official experts to provide command-line parameters!

**Comment by mkj** [comment]
The `-D` option was added a few days ago in #330 , so you'll have to build from the latest git tree.

**Comment by worm001** [comment]
> The `-D` option was added a few days ago in #330 , so you'll have to build from the latest git tree.

Okay~Thank you, boss! I'll go research it.

**Comment by mkj** [comment]
This is now implemented thanks to Darren Tucker in #330
