### ISSUE TITLE
dropbear (2024.86 - 22 October 2024) can't connect to an SSH-2.0-CerberusFTPServer_9.0 server -- "Bad hostkey signature"

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [mkj/dropbear#329]
When I try connecting with an empty known hosts file the RSA key is accepted, but then the connection is immediately cut with a bad hostkey signature.

Connections with OpenSSH 9.9 work ok (with HostKeyAlgorithms +ssh-rsa).

The RSA public key received by OpenSSH and dropbear are the same:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzU2lGKpdz59OB7UuWP0Vo3VzrOzyZANK2LXNuL7TiqW81HcJxbImzcDvpEVqHQ/a3Ok+7dRnYZ8iwFzJjy5noydMJ1F+dIRWTtumh2gFJ2T5Avv2OQoc+cNwRg0e1XOvRIGf5wZXcdrzZGysl9EaiKJC2yp4d6wdRfE3IW/ITP2QUMZsl+cTRzjMFQskhNonIRavURoxnYai0BkjqJTavf8rj+DBvpkzFvAaQfXEYRGbxGQprp416I1dYd7jE6fxE13Pasyx7MuskmmpK0nTRnpkYYQYuPhhrwPhZLFNj9ln2i1qBOMHptVF3ghPD/pXgnTboAs/olX3/e9eTohUd

Here's the end of the trace info:

TRACE4 (10455) 0.073984: process_packet: packet type = 31,  len 701
TRACE4 (10455) 0.073992: got expected packet 31 during kexinit
TRACE4 (10455) 0.074003: enter recv_msg_kexdh_reply
TRACE4 (10455) 0.074010: keytype is 0
TRACE4 (10455) 0.078853: checkpubkey: base64_decode success
TRACE1 (10455) 0.078901: server match SHA256:i0kZ44976ponB8KhSoZp5A0Y38ginfUJ8fLlSdSw/00
TRACE4 (10455) 0.080019: enter buf_get_rsa_pub_key
TRACE4 (10455) 0.080108: leave buf_get_rsa_pub_key: success
TRACE4 (10455) 0.080125: enter buf_get_ecc_raw_pubkey
TRACE4 (10455) 0.087662: enter buf_put_rsa_pub_key
TRACE4 (10455) 0.087710: leave buf_put_rsa_pub_key
TRACE4 (10455) 0.087796: enter buf_verify
TRACE4 (10455) 0.087830: enter buf_rsa_verify
TRACE4 (10455) 0.087994: leave buf_rsa_verify: ret -1
TRACE4 (10455) 0.088025: Exited, cleaning up: Bad hostkey signature
TRACE4 (10455) 0.088034: enter session_cleanup
TRACE4 (10455) 0.088041: enter chancleanup
TRACE4 (10455) 0.088048: leave chancleanup
TRACE4 (10455) 0.088059: enter cli_tty_cleanup
TRACE4 (10455) 0.088066: leave cli_tty_cleanup: not in raw mode
TRACE4 (10455) 0.088075: leave session_cleanup

./dbclient: Connection to john@xxx:22 exited: Bad hostkey signature

What more information could I usefully provide?

**Comment by mkj** [comment]
The full trace might have some hints, it'll indicate which algorithms should be negotiated. If you can get a packet capture of tcp port 22 (Wireshark?) that might show something too.

**Comment by JohnHughesAtlantech** [comment]
Here's the dbclient trace-4 output:
[trace-4.txt](https://github.com/user-attachments/files/17733487/trace-4.txt)
