### ISSUE TITLE
How to Enable X11 forwarding for dropbear?

### ISSUE THREAD

**Issue by snowdream** [mkj/dropbear#336]
I want to install [dropbear](https://github.com/mkj/dropbear) on alpine 3.21.0 and debian 12.8.0, and Enable X11 forwarding for dropbear.

But i do now know what to do?

What configuration should i modify? 

or what arg should i use to start dropbear?

**Comment by mkj** [comment]
You should be able to build Dropbear server with a file `localoptions.h` with contents

```
#define DROPBEAR_X11FWD 1
```

Only Dropbear server supports x11 forwarding - you'll have to use openssh client.

**Comment by snowdream** [comment]
Is x11 forwarding feature enabled default?(Alpine, Debian)

Or I have to build from source myself to support x11 forwarding.

**Comment by mkj** [comment]
It looks disabled in debian, not sure about alpine.

**Comment by snowdream** [comment]
@mkj Thank you.
